music/urls.py
from django.urls import path
from music import views


urlpatterns = [
    path('home/', views.home, name='homepage'),
    path('contactus/', views.contactus, name='homepage'),
    path('home/albums/', views.albums_list, name='albums_list'),
    path('home/albums/create/', views.AlbumCreate, name='albums_create'),
    path('home/albums/<int:id>/', views.album_detail, name='album_detail'),
    path('media/', views.media_error, name='media_error'),
]

music_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models


# Create your models here.
def store_image(instance, filename):
    return './'.join(['images', filename])


def mp3(instance, filename):
    return './'.join(['musics', filename])


class Album(models.Model):
    singer = models.CharField(max_length=30)
    title = models.CharField(max_length=50)
    genre = models.CharField(max_length=20)
    logo = models.ImageField(blank=True, null=True, upload_to=store_image) #! it can be FileFiled 

    def __str__(self):
        return f'{self.singer} --- {self.title}'


class Song(models.Model):
    title = models.CharField(max_length=40)
    file_type = models.CharField(max_length=20) # Just for View the file type
    file = models.FileField(blank=True, null=True, upload_to=mp3)
    description = models.TextField(default="description for the song", max_length=500)
    album = models.ForeignKey(Album, on_delete=models.CASCADE) #* the album that the song belongs to

    def __str__(self):
        return self.title

music/forms.py
from django import forms
from .models import Album


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = [
            'singer',
            'title',
            'genre',
            'logo'
        ]

music/views.py
from django.shortcuts import render
from .forms import AlbumForm
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from .models import Album


# Create your views here.
def home(request):
    return render(request, 'home.html')


def contactus(request):
    return render(request, 'contactus.html')


def albums_list(request):
    queryset = Album.objects.all()
    return render(request, 'albums_list.html', {'albums': queryset})


def album_detail(request, id=None):
    queryset = get_object_or_404(Album, id=id)
    return render(request, 'album_details.html', {'instance': queryset})


def AlbumCreate(request):
    form = AlbumForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False) #* commit=False is used to save the object in the memory not in the db yet.
        instance.save()                    #? i will try to run the app without it.
        return HttpResponseRedirect('/home/albums/')
    return render(request, 'albums_create.html', {'form': form})#? i will try to run the app without it.


def media_error(request):
    return render(request, 'media_error.html')

templates/album_details.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col">
        <div class="container ml-1">
            <h1 class="mt-5 text-primary"><span>Album Name: </span>{{ instance.title }}</h1>
            <h2 class="text-primary"><span>Singer Name: </span>{{ instance.singer }}</h2>
            <h3 class="text-primary"><span>Genre: </span>{{ instance.genre }}</h3>
            <img class="img-fluid" alt="Responsive image" src="/media/{{ instance.logo }}">
        </div>
    </div>
    <div class="col">
        <div class="rounded container bg-primary mt-5">
        {% for song in instance.song_set.all %}
        <br>
            <div class="container row">
                <div class="card border-0 ml-4" style="width: 600px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ song.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ instance.singer }}</h6>
                        <p class="card-text">{{ song.description }}</p>
                        <button class="btn btn-primary"><a href="/media/{{ song.file }}" class="text-light">Download</a></button>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/albums_create.html
{% extends 'base.html' %}
{% block content %}
 <div class="row">
         <div class="col-md-4 mx-auto mt-5">
            <div class="myform form ">
               <form action="" method="POST" enctype="Multipart/form-data">
               {% csrf_token %}
                  <div class="form-group">
                     <input type="text" name="singer"  class="form-control my-input" id="singer_name" placeholder="Singer Name">
                  </div>
                  <div class="form-group">
                     <input type="text" name="title"  class="form-control my-input" id="album_title" placeholder="Album Title">
                  </div>
                  <div class="form-group">
                     <input type="text" name="genre" id="genre"  class="form-control my-input" placeholder="Genre">
                  </div>
                  <div class="text-center ">
                     <button type="submit" name="Create Album"class=" btn btn-primary">Create The Album</button>
                  </div>
               </form>
            </div>
         </div>
      </div>
{% endblock %}

templates/albums_list.html
{% extends 'base.html' %}
{% block content %}
<ul class="mt-5 list-group">
{% for album in albums %}
  <a class="mt-1 text-white bg-primary list-group-item" href="{{ album.id }}/">{{ album.title }}</a>
{% endfor %}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type='text/css' href="{% static 'css/style.css' %}">
    </head>
    <body>
        <header class="navbar navbar-dark bg-primary">
            <a class="navbar-brand" href="/home/">Music</a> <!--Logo here-->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/contactus/">Contact Us</a>
                </li>
            </ul>
        </header>
        {% block content %}{% endblock %}
    </body>
</html>

templates/contactus.html
{% extends 'base.html' %}
{% block content %}
<h1>Contact Us Page</h1>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 class="text-center mt-5">Welcome To Music App</h1>
    <p></p> <!--Under Construction-->
    <br></br>
    <div class="col text-center mt-5">
        <a class="btn btn-primary" href="albums/"><h4>Albums List</h4></a>
    </div>
    <div class="col text-center mt-5">
        <small>login to add your own album list</small><br>
        <small>name: test <br> password: 123</small>
    </div>
    <div class="col text-center mt-1">
        <a class="btn btn-primary" href="/admin/"><h4>Login</h4></a>
    </div>
</div>
{% endblock %}

templates/media_error.html
{% extends 'base.html' %}
{% block content %}
<div class="m-5 text-center container">
    <h1 class="text-primary">Sorry This Song Is Not Exsisted</h1>
    <p>This happens when the user din't upload the song file</p>
</div>
{% endblock %}